name: CI

env:
  TESTING_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7EWYjTFGlz8yf
    ZUfpqBA9wylQ8Xj1mOX6Zh+7wUsa5EdNkqz1tCnnj27BrhqECdwASVkXYZoKexFk
    VSiflUvevH2NHtW7zofgp5AZClka+ollqvwktAnsCBxZIKmapIHEHA/efoCFm3Df
    GyOyExsR4H6QnHudX6MfKep0CNSu01w4mi8IzSx9QAcQSCysbwdhvU74gNTr8FGG
    7++Cd/A4RNdYDGTUR78221AuokQvMCZWlvbNKxQQCPN0TN8GFPOd9NXELoP+g4WE
    srwDrhJV4nPRqXUUnk2aRNQF6VrFLk5mQ9HcOGzTkkTzPLeyLUQJcsyhDD9KoFCb
    MtHYqyfXAgMBAAECggEATnJ2bZkEqE8jFTjo1lB3Nx9PhTUuL3gGAWKwLhFaCJXw
    XNSEmakK5aNdo/T6A6MK0kfwB4ETkw+W9IdNuNZn8akD0Zk7sj1i98/s+sM/KLQl
    yC/S+yVQ/91K3gl3dnVEQdQux3QvO1g7FiSQbI3cjTuid8xXfmBrzJbMTgqh/gnG
    uCFcTMM5K1a+3lzSUwhKu/HGU05bKxSBHJBQLwRgEh4ko/KQbQSrDlkEZoYV8Ql6
    rP+/OpA9pSCaJJsN6D+XRWQq3w0n2EpidtLWBu56ZwXS4XiSoy70QLl9bxRfw6Sf
    jh721q4YWnNA0qkuBYjCJAGOVYPeFcg9s7jICrzJOQKBgQDpWmxl2HFyRkX1DITt
    wSxuWgAJm8aYlaT8Gda+q5MkNG2DNUw8P7nFtAFbbV0BaPRxw7BiqQoo0wRy4juz
    3xnCpNGxOUzsT8cjIHBBOY1Qcf9K26AqwsK7F950XSGJvUwMK3mHemojif774unr
    1SqV9H6UXA3IBSfgWmN/g1Ja6wKBgQDNOQj/X0p8euIEeq3OUCmD2voMPii7u3KA
    N8t9GNZxIn6KsSUSdh9B9j45NGqLOV7Cg4I1hJuAGHRaOCro96qc7rW6Y3EgQLKK
    c+8MRWL7nBFYC35Uk+KZ19jvfm/gYaqB6ut60DJa+wR+25nyNLY6DIlDdx2GfFwd
    6QWvbjNTxQKBgC0OZourpQv5gZx1FF2LxPZxrjwstcXUbwy2OH6MRlbhQJvq+JNR
    gp8nyHNMxH53M2ub6zzBgtKrG9rKz9hFJYYtqMddVvrx1HN12fbeE+kKec6MZXqc
    LFlPnIY/TTB5OmvHISoFeuTtyiv8fkoo2JYnpSEkPQz34eEx0rBWPNqNAoGAL6Ah
    12nc1mCKHTH/Ldbqm3/w8XBncZHBs8G/BowCEAVKSpNroAornNoxfIMOirrIo+lz
    CUp579M9BUbtplz7iinXoKa9NRfulzTqb/WWT//bAozAR45+UueFn6a+/dqMgFPt
    S/YPCZAhbfM2mb/j3jrUjASTpIcttX9DY3/2h2UCgYEAqf00ZmFeu0F9LXBqH3IC
    0SZAUKtC5tqIQTNmaGr2xlHWVxyYXEBKLD5LitiuXCagWJP/klWzlTACvVhhXSYw
    3hMBoueWtnscA1iOzCO9kMjJ7+IMPTUTQobxm9y8D9VaZh+F/63t2HI1JO9lvlod
    BlBzCoN89VjyDCI6uN2iXOI=
    -----END PRIVATE KEY-----

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        elixir_version: [1.15, 1.16, 1.17]
        otp_version: [ 25, 26, 27]
        exclude:
          - otp_version: 27
            elixir_version: 1.15
          - otp_version: 27
            elixir_version: 1.16

    steps:
      - uses: actions/checkout@v5

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_version}}
          elixir-version: ${{matrix.elixir_version}}

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp_version }}-${{ matrix.elixir_version }}

      - run: mix deps.get

      - run: mix deps.unlock --check-unused

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors

      - run: mix credo --strict --format=oneline

      - run: mix test --warnings-as-errors --cover

  dialyzer:
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v5

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.16
          otp-version: 26

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}

      - run: mix deps.get

      - name: Restore PLT cache
        id: plt_cache_restore
        uses: actions/cache/restore@v4
        with:
          key: |
            plts-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            plts-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-
          path: |
            priv/plts

      - name: Create PLTs
        if: steps.plt_cache_restore.outputs.cache-hit != 'true'
        run: mix dialyzer --plt

      - name: Save PLT cache
        id: plt_cache_save
        if: steps.plt_cache_restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: |
            plts-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          path: |
            priv/plts

      - name: Run dialyzer
        run: mix dialyzer --format github --format dialyxir

  check_format:
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v5

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.17
          otp-version: 27

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}

      - run: mix deps.get

      - run: mix format --check-formatted
